"""Database package — re-export every public function (one import surface)."""
from .core import (
    close_db,
    get_pool,
    init_db,
    to_db_utc,
    utcnow,
)
from .subscriptions import (
    clear_panel_uuid,
    create_gift,
    create_pending_payment,
    due_reactivation_offers,
    due_reminders,
    due_trial_end_offers,
    expired_active,
    get_payment,
    get_subscription,
    has_paid_payment,
    is_payment_paid,
    mark_expired,
    mark_payment_failed,
    mark_payment_paid,
    mark_payment_refunded,
    mark_react_offer_sent,
    mark_reminder_sent,
    activity_windows,
    payment_history,
    payments_count,
    payments_page,
    recipients,
    redeem_gift_record,
    revenue_windows,
    segment_count,
    revoke_subscription,
    stats,
    upsert_subscription,
    ACTIVITY_WINDOWS,
    REVENUE_WINDOWS,
    SEGMENTS,
)
from .users import (
    claim_trial,
    clear_offer,
    credit_referral,
    find_user_by_username,
    get_user,
    mark_reachable,
    mark_trial_offer_sent,
    mark_unreachable,
    referral_leaderboard,
    referral_leaderboard_count,
    referral_stats,
    release_trial,
    set_offer,
    set_referral,
    trial_available,
    upsert_user,
)

__all__ = [
    # core
    "init_db",
    "close_db",
    "get_pool",
    "utcnow",
    "to_db_utc",
    # users
    "upsert_user",
    "get_user",
    "find_user_by_username",
    "mark_unreachable",
    "mark_reachable",
    "trial_available",
    "claim_trial",
    "release_trial",
    # referrals
    "set_referral",
    "credit_referral",
    "referral_stats",
    "referral_leaderboard",
    "referral_leaderboard_count",
    # offers
    "set_offer",
    "clear_offer",
    "mark_trial_offer_sent",
    # subscriptions
    "get_subscription",
    "upsert_subscription",
    "clear_panel_uuid",
    "create_pending_payment",
    "get_payment",
    "is_payment_paid",
    "has_paid_payment",
    "mark_payment_paid",
    "mark_payment_failed",
    "mark_payment_refunded",
    "revoke_subscription",
    "due_reminders",
    "mark_reminder_sent",
    "expired_active",
    "mark_expired",
    "due_trial_end_offers",
    "due_reactivation_offers",
    "mark_react_offer_sent",
    "stats",
    "revenue_windows",
    "activity_windows",
    "REVENUE_WINDOWS",
    "ACTIVITY_WINDOWS",
    "SEGMENTS",
    "payment_history",
    "payments_count",
    "payments_page",
    "recipients",
    "segment_count",
    # gifts
    "create_gift",
    "redeem_gift_record",
]
